name: aas-asdf

dependencies:
  - jupyter
  - notebook >= 6.0
  - matplotlib >= 3.2
  - ipympl
  - numpy >= 1.20
  - packaging
  - pip
  - python == 3.12
  - pyyaml
  - stdatamodels == 2.1.2
  - roman_datamodels == 0.22.0
  - pip:
      - asdf
      - asdf-astropy
      - lz4
      - astropy >= 5.3
      - gwcs >= 0.20
